package paygateway

const (
	CodeOK                        = "OK"
	CodeInvalidRequest            = "INVALID_REQUEST"
	CodeInvalidSignature          = "INVALID_SIGNATURE"
	CodeTimestampExpired          = "TIMESTAMP_EXPIRED"
	CodeReplayedRequest           = "REPLAYED_REQUEST"
	CodeAppNotFound               = "APP_NOT_FOUND"
	CodeAppDisabled               = "APP_DISABLED"
	CodeIPNotAllowed              = "IP_NOT_ALLOWED"
	CodeMissingRequiredField      = "MISSING_REQUIRED_FIELD"
	CodeInvalidAmount             = "INVALID_AMOUNT"
	CodeInvalidCurrency           = "INVALID_CURRENCY"
	CodeCurrencyNotSupported      = "CURRENCY_NOT_SUPPORTED"
	CodeInvalidReturnURL          = "INVALID_RETURN_URL"
	CodeInvalidMetadata           = "INVALID_METADATA"
	CodeOrderNotFound             = "ORDER_NOT_FOUND"
	CodeOrderAlreadyPaid          = "ORDER_ALREADY_PAID"
	CodeOrderExpired              = "ORDER_EXPIRED"
	CodeOrderStatusNotAllowed     = "ORDER_STATUS_NOT_ALLOWED"
	CodeIdempotencyConflict       = "IDEMPOTENCY_CONFLICT"
	CodeRefundNotFound            = "REFUND_NOT_FOUND"
	CodeRefundAmountExceedsPaid   = "REFUND_AMOUNT_EXCEEDS_PAID"
	CodeRefundStatusNotAllowed    = "REFUND_STATUS_NOT_ALLOWED"
	CodeChannelUnavailable        = "CHANNEL_UNAVAILABLE"
	CodeChannelConfigInvalid      = "CHANNEL_CONFIG_INVALID"
	CodeChannelResponseError      = "CHANNEL_RESPONSE_ERROR"
	CodeChannelTimeout            = "CHANNEL_TIMEOUT"
	CodeChannelNotifyVerifyFailed = "CHANNEL_NOTIFY_VERIFY_FAILED"
	CodeInternalError             = "INTERNAL_ERROR"
	CodeServiceUnavailable        = "SERVICE_UNAVAILABLE"
	CodeRateLimited               = "RATE_LIMITED"

	// CodeInvalidResponse is generated by the SDK when the gateway response
	// cannot be decoded as the standard API envelope.
	CodeInvalidResponse = "INVALID_RESPONSE"
)
